apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 31111
  selector:
    app: nginx
  type: NodePort

